### ISSUE TITLE
Consider changing the api's url

### ISSUE THREAD

**Issue by hqy2000** [fjcaetano/ReCaptcha#10]
For some reasons, all google.com domains are blocked in China. However, Google has just set up a domain called recaptcha.net and users in China can access through Google's server in Beijing.
So I suggest that you may change the url for people in China to access the service.
The url is https://www.recaptcha.net/recaptcha/api.js, (its certificate is issued by Google Internet Authority, so it is REAL)

**Comment by fjcaetano** [comment]
@mmlmml1 could you check if the branch `feature/alternate-endpoint` is working for you? Take a look at the branch's README, you should be able to change your ReCaptcha init to:
``` swift
ReCaptcha(endpoint: .alternate)
```

**Comment by hqy2000** [comment]
@fjcaetano Sure, and it works! Thx!
