### ISSUE TITLE
Is there any way to center CAPTCHA widget on the screen?

### ISSUE THREAD

**Issue by DarkSatyr** [fjcaetano/ReCaptcha#100]
iOS 13.4
Device: iPhone X

Captcha widget appears on the upper-left side of screen 
![IMG_0006 1](https://user-images.githubusercontent.com/20116857/103089985-6bef8f80-45f8-11eb-9549-4ca112b745b4.PNG)

**Comment by DarkSatyr** [comment]
Found a solution:
Since captcha has fixed size...
`let width = min(302, viewController.view.bounds.width)`
`let height = min(516, viewController.view.bounds.height)`
`webView.frame = CGRect(center: viewController.view.bounds.center, size: CGSize(width: width, height: height))`

Inside configureWebView closure

**Comment by vassily-fr** [comment]
> Found a solution:
> Since captcha has fixed size...
> `let width = min(302, viewController.view.bounds.width)`
> `let height = min(516, viewController.view.bounds.height)`
> `webView.frame = CGRect(center: viewController.view.bounds.center, size: CGSize(width: width, height: height))`
> 
> Inside configureWebView closure

But what if google choose to change size one day ?
Is there a another way to performe the "center"

**Comment by fjcaetano** [comment]
Webviews usually have a hard time figuring out the size of their contents. You can try and set the frame based on the `contentSize`, but your best bet would be to use a fixed size
