### ISSUE TITLE
Validate callback not getting called

### ISSUE THREAD

**Issue by v11021** [fjcaetano/ReCaptcha#102]
https://www.compnyname.com ? 
3. You are using an **Invisible** reCAPTCHA v2 key. --- YES 
4. If the widget doesn't appear, that is expected since the library will try to resolve the challenge _invisibly_.
5. 1. You are using the **SITE** key  -- YES
2. The correct domain, with protocol, is setup.   ---- Does the domain have to be like ths --> https://www.compnyname.com ? 
3. You are using an **Invisible** reCAPTCHA v2 key. --- YES 

https://www.google.com/recaptcha/admin#site
-->

## Bug description
I am trying to integrate Recaptcha in my ios application. I followed all the steps but my validate methods callback is never getting called even after trying multiple times. 
I am using site key and domain as https://www.compnyname.com is that correct?

**Comment by v11021** [comment]
@fjcaetano can you please help.

**Comment by fjcaetano** [comment]
Is that domain you described the same one that have been configured on the ReCaptcha website?

Also, please post whatever is being logged if you can. There's not enough information there to infer what might be happening

**Comment by v11021** [comment]
@fjcaetano thanks for your reply. Actually I just tried again and it worked fine. 
Though first time it showed me the captcha to solve images but next few tries it silently succeeded. Is there any way to do even the first time silently(invisibly)

**Comment by fjcaetano** [comment]
That logic is handled by the Google library. I kinda makes sense to show the challenge at first because it doesn't really know if the user is a human or a computer.

I'm closing this issue since your situation seems to have solved itself, but feel free to reopen it or create a new one if you need.
