### ISSUE TITLE
reCaptcha not working for iOS 15.1.1 

### ISSUE THREAD

**Issue by davo156** [fjcaetano/ReCaptcha#115]
## Bug description
As the title says, the reCaptcha won't load on iOS 15.1.1 with and iPhone 13 pro. To be more specific, when performing the validate method, the webview wont appear above the current view. 

I followed the path, and before the executeJS method is called, the webview must be set to visible, but this do not happen. So because of this, the webview never appears and the validate won't throw any errors.

This bug don't happened on older versions, like iOS 14.6 or lesser.

## To Reproduce
Run on iPhone 13 Pro - iOS15.1.1

1. Setup the reCaptcha
```
let recaptcha = try? ReCaptcha(
    apiKey: Constants.captchaKey,
    baseURL: URL(string: Constants.captchaURL)!,
    endpoint: .alternate
)
```

2. Configure the reCaptcha
```
recaptcha?.configureWebView { [weak self] webview in
    webview.frame = self?.view.bounds ?? CGRect.zero
}
```

3. Validate
```
recaptcha?.validate(on: view) { [weak self] (result: ReCaptchaResult) in
    // the callback will never be called
}
```

## Expected behavior
The expected behavior should be the same as the older versions, to add the webview to the current view and show the captcha images.

## Logs
The reCaptcha library don't throws any errors.

## Additional context
We are using the .alternate endpoint but the error is present regardless if is .default or .alternate

**Comment by p01Sawsans** [comment]
I am facing this same issue also (reCaptcha not working ) for iOS versions 15.0+ .

**Comment by fjcaetano** [comment]
I'm not being able to reproduce this issue. Did anyone investigate this further?

**Comment by oldlf** [comment]
Works fine on ios 15.2.1 - iPhone X.

**Comment by hinaHingrajia** [comment]
Works fine on iOS 15.5
