### ISSUE TITLE
ReCAPTCHA challenge not showing in the library example.

### ISSUE THREAD

**Issue by light-cloud** [fjcaetano/ReCaptcha#128]
## Bug description
ReCAPTCHA challenge not loading in the library example.

## To Reproduce
Steps to reproduce the behaviour:
1. Download the library.
2. Open Example project.
3. Set correct siteKey and site url.
4. Run the code. Force the challenge to appear. 

## Actual behaviour
White screen. Challenge not displayed.

## Expected behaviour
ReCAPTCHA challenge with pictures appears.

**Comment by kubatruhlar** [comment]
It seems like it has generally stopped showing challenges, regardless of the site keys/domains used for initialization. FYI @fjcaetano

**Comment by ghost** [comment]
Added possible fix with css rule for width height.
https://github.com/fjcaetano/ReCaptcha/pull/129

**Comment by fsljivo** [comment]
It stopped working for me too

**Comment by Ded77** [comment]
Thank you @light-cloud, your PR fixes the issue!

**Comment by thedemonswithin** [comment]
Thank you @light-cloud, it works now

**Comment by morluna** [comment]
Hi all, we believe our app was affected by this. Will we need to bump the version or should this fix resolve the issue without need to upgrade?

**Comment by fjcaetano** [comment]
I don't have an estimate of when this will be released as a new version. In the meantime, you should be able to update the lib with these changes by pointing to the commit `dc2b4414e707fb55db7f075c1456f10fda43191c`, currently at the head of the `master` branch.
