### ISSUE TITLE
Screen goes blank when tapping outside image area.

### ISSUE THREAD

**Issue by xmidi** [fjcaetano/ReCaptcha#14]
Once the recaptcha image is visible, if you tap on an area near the edge of the screen.  The screen goes blank.  This was reproducble on all devices tested using iOS 11.x.

**Comment by fjcaetano** [comment]
That's interesting. It's a behavior from Google's API. I believe it thinks you're dismissing it by tapping outside of the div's frame.

Have you tried decreasing the webview's frame size to match the div's borders precisely?

**Comment by xmidi** [comment]
I have not tried matching the div size to the webView size, we currently have the webview edge to edge.  I _think_ it might be a chicken/egg, if we decrease the webview frame, the div might decrease as well, but I will try it.

**Comment by xmidi** [comment]
So, swing-and-a-miss, decreasing the size of the webView didn't help.  Tapping around the edges still makes the recaptcha image disappear.

**Comment by fjcaetano** [comment]
@xmidi could you check if the branch `fix/div-dismiss` fixes it for you?

**Comment by ssathy2** [comment]
I was having this exact same problem and the `fix/div-dismiss` branch fixes it for me.

**Comment by fjcaetano** [comment]
@ssathy2 that's nice to know.

@xmidi if you can confirm this fixes it for you as well, I may start working on releasing this fix

**Comment by xmidi** [comment]
Excellent, works for me too, thanks!
