### ISSUE TITLE
[BUG] UI API called on a background thread

### ISSUE THREAD

**Issue by Nexmind** [fjcaetano/ReCaptcha#15]
[BUG]
Hello,
I'm facing a crash when i initialize my Recaptcha.
`fileprivate let recaptcha = try! ReCaptcha()`

After something like 0.5 secondes, the app crash with  a Main Thread Checker: UI API called on a background thread. 

I've no request with ui modification in my viewDidLoad. Maybe you should check if you've not forget to force an UI API call in the main thread on your side ? 

I will investigate it too. 

Kind Regards

**Comment by fjcaetano** [comment]
@Nexmind when and where in the API is the exception occurring? Could you post a full log of the error description here?

**Comment by Nexmind** [comment]
Hello,
In fact the UI API error message came in the same time than the crash but wasnt the cause. 

The cause of the crash was the recaptcha domain in my plist was not correct. I fixed it and now it work perfectly :-)

**Comment by fjcaetano** [comment]
Awesome, glad to know it's working. Thanks
