### ISSUE TITLE
Validation fails when `baseURL` has no protocol

### ISSUE THREAD

**Issue by fjcaetano** [fjcaetano/ReCaptcha#18]
If the provided `baseURL` has no protocol (http, https, etc), the validation fails silently.

May be related to #17

**Comment by MaximusMcCann** [comment]
@fjcaetano this was my problem. had to pre-pend "https://"

**Comment by fjcaetano** [comment]
Cool, this fix does just that. I've also updated the README to make it a little clearer. Thanks for the input. I'll be releasing this soon
