### ISSUE TITLE
Webview content broken on iPhone X

### ISSUE THREAD

**Issue by diegotl** [fjcaetano/ReCaptcha#22]
The webview content breaks if rendered below 43px from the top of the iPhone X. This not related to the webview's width and height. The pictures attached shows reCaptcha webview inside a container view located at `[0, 43]`, which looks fine, and the broken one located at `[0, 44]`.

The weird part is that this is reproducible only on a real iPhone X device. I've tried other iPhones/iPad devices and simulators, including iPhone X simulator, both running 11.2.6 and 11.3 beta 3 and this issue only happens on a real iPhone X.

I guess it's somehow related to the webview adjusting the content inset. But disabling this feature doesn't fix it.

![img_0861](https://user-images.githubusercontent.com/34442011/36858529-291fb56e-1d5a-11e8-9953-173a1b8bef3f.PNG)
![img_0862](https://user-images.githubusercontent.com/34442011/36858531-29502c76-1d5a-11e8-8761-58d8dc87bbe9.PNG)

Also, `configureWebView` gets called many times, even after challenge has finished. And it also gets called many minutes after that.

**Comment by fjcaetano** [comment]
If this only happens on iPhone X, it's definitely related to safe area. About your guess, `WKWebView` doesn't have insets, so that wouldn't be it.

When you say it breaks below 43px, does it means that any value for `origin.y > 43` it breaks? Or is it the other way around: `origin.y < 43`?

In which view are you adding the webview? Is it just a regular UIView in your view controller?

Also, just so I can get a sense of priority: are you being able to use ReCaptcha in any way?

**Comment by diegotl** [comment]
If the webView is rendered on any origin.y > 43 it breaks. It works if rendered below that value and moved to any part of screen, but that's a dirty solution.

I've tried in the current viewController's view, and tried inside a container view (which is inside the current viewController). Got the same behaviour on both.

ReCaptcha itself works, but when it breaks I can't select the options, nor scroll to see them. So when it breaks it becomes unusable.

**Comment by fjcaetano** [comment]
@diegotl I'm having a hard time reproducing this. I'll leave it open, so feel free to post any updates you see fit

**Comment by diegotl** [comment]
I'll upload a sample project so you can reproduce it later. Thanks

**Comment by diegotl** [comment]
@fjcaetano I can't reproduce it again. Maybe it was a bug on 11.3 beta 3 (I'm running beta 4 now) or maybe it was somehow related to some google-side stuff, idk... I'll keep observing for the following days. Thanks!

**Comment by diegotl** [comment]
I think you can close it, I couldn't reproduce it again since then.

Thanks!

**Comment by fjcaetano** [comment]
Awesome. Thanks for the feedback @diegotl
