### ISSUE TITLE
Support recaptcha `reset`

### ISSUE THREAD

**Issue by fjcaetano** [fjcaetano/ReCaptcha#23]
A [`reset`](https://developers.google.com/recaptcha/docs/invisible#js_api) method has been released for the JS API.

This may enable us to stop having to allocate a new instance of ReCaptcha whenever an error occur.

**Comment by MaximusMcCann** [comment]
What version will this be in?  Not seeing it in v1.1 :/

**Comment by MaximusMcCann** [comment]
Ah, just noticed how new this is...

**Comment by fjcaetano** [comment]
@MaximusMcCann yes, this was just implemented 🎉 

I'll be releasing this soon. Meanwhile, you can use this by pointing to the `master` branch

**Comment by fjcaetano** [comment]
@MaximusMcCann this has been released with version `1.2` 🚀
