### ISSUE TITLE
Update code for Swift 4

### ISSUE THREAD

**Issue by lamhuynh96** [fjcaetano/ReCaptcha#3]
Hi guy, 
I'm very interested in your work and want to use this for reCaptcha in my app. But there's too much error and obsoleted when running it with Xcode 9 and Swift 4.
I hope you can modify this to work with Swift 4. In that case, I'm very appreciated.
Thank you.

**Comment by lamhuynh96** [comment]
I just check if just import pod 'ReCaptcha',  it runs with no error.

**Comment by fjcaetano** [comment]
@lamhuynh96 feel free to open a pull-request with these fixes. It'd be much appreciated.

Since Swift 4 is still in beta, I believe it would be best to have it in a branch called `swift4` that we can merge onto master when it's properly released.
