### ISSUE TITLE
Endless cycle of executing/resetting

### ISSUE THREAD

**Issue by yehoshuanagel** [fjcaetano/ReCaptcha#35]
Hi,

I am trying to use ReCaptcha v1.2 and when calling validate, I get an endless loop of log statements:
[JS LOG]: resetting
[JS LOG]: executing
[JS LOG]: resetting
[JS LOG]: executing
etc etc

Any ideas?

**Comment by fjcaetano** [comment]
@yehoshuanagel could you try sending `resetOnError: false` and capturing the error thrown?

**Comment by yehoshuanagel** [comment]
Unexpected Error: Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=24, WKJavaScriptExceptionMessage=TypeError: Argument 1 ('target') to MutationObserver.observe must be an instance of Node, WKJavaScriptExceptionColumnNumber=13, WKJavaScriptExceptionSourceURL=<myUrl>, NSLocalizedDescription=A JavaScript exception occurred}

**Comment by fjcaetano** [comment]
It looks like a duplicate of #7.

Could you check if you have configured the domain and key correctly?

**Comment by yehoshuanagel** [comment]
All good. Thanks
