### ISSUE TITLE
Validate doesn't respond if it's called second time

### ISSUE THREAD

**Issue by hamdshah** [fjcaetano/ReCaptcha#36]
If I call the `validate` function for the second time it doesn't respond, the log only says
 `[JS LOG]: executing`
 and the completion is not called waiting forever.

The bug can be reproduce in the "Example" project also, tapping validate button first time works but not the second time.

**Comment by fjcaetano** [comment]
@hamdullahshah as it happens to the JS lib, you cannot validate multiple times without resetting it. Please, try calling `recaptcha.reset()` in between your validation calls.

**Comment by hamdshah** [comment]
Sorry for late reply,
I tried and same behaviour with `recaptcha.reset() `.
One thing more that i noticed while testing this that if i call `recaptcha.reset() ` without calling the `validate()` function first,  then it even stuck on first try.

**Comment by fjcaetano** [comment]
That is super weird. I'm not being able to reproduce it and it will be hard to try and look at anything without more data.

Could you share your logs (without any sensitive data) and/or share a project where this behavior happens?

**Comment by fjcaetano** [comment]
@hamdshah I may have found something. Could you check if the branch `fix/reset` solves the issue for you?

I'd also appreciate if you could approve PR #37 if everything is good.

**Comment by hamdshah** [comment]
Just to be sure that I am doing it correct, If I change the function in Example project with the following one it suppose to work right ?

``` swift
    var resetCalled = 0
    @IBAction func didPressSegmentedControl(_ sender: UISegmentedControl) {
        if restCalled > 0 {
         recaptcha.reset()
        }
        resetCalled += 1  
        label.text = ""
        switch sender.selectedSegmentIndex {
        case 0: setupReCaptcha(endpoint: .default)
        case 1: setupReCaptcha(endpoint: .alternate)
        default: assertionFailure("invalid index")
        }
    }
```

But it's not working :) I will also try to debug internally if I get some time on weekend.

**Comment by fjcaetano** [comment]
No, that should not be necessary considering that `setupReCaptcha` creates a new instance, which would be similar to resetting it.

What you could do on the Example project is call `reset` after you receive a token. This way ReCaptcha would be ready to validate again after it has finished the validation cycle.

But if simply changing the segmented control should work regardless of calling ReCaptcha, because it creates a new instance, as I said. If even that is not working, I'd suggest you to check if you're using the correct key and domain, and if you don't have any firewall limitations.

**Comment by fjcaetano** [comment]
Hey @hamdshah, sorry for the late late reply. I was able to reproduce your issue, but the solution didn't quite work as expected.

Now, `configureWebView` doesn't get called multiple times, but after 10 minutes, when the update happens, the whole webview goes white without displaying the new content.

I'd love if you could take a look at that and check if the code works for you or what's the behavior on your end.
