### ISSUE TITLE
WKWebView content is not centered

### ISSUE THREAD

**Issue by vol24pl** [fjcaetano/ReCaptcha#38]
When the WKWebView is loaded, the content of the webView is aligned left.

![screen shot 2018-05-07 at 16 38 07](https://user-images.githubusercontent.com/7266741/39707549-0de0a322-5215-11e8-86a3-6fb1627c9f4a.png)

 After Clicking anything that would refresh content (for example circled "i" icon with info), it will center itself.

![screen shot 2018-05-07 at 16 38 27](https://user-images.githubusercontent.com/7266741/39707564-162b2eee-5215-11e8-9c44-bfeed1128c9b.png)

Any ideas how to center it at the begining?

I think it loads content before the webView have bounds, and after getting the new bounds, the content doesn't reposition itself (untill "i" icon is tapped).

**Comment by fjcaetano** [comment]
It is indeed weird that the captcha is being centralized after tapping on the info button. But I believe it shouldn't be centralized in the webview by default.

That may not be the case for every user, and you may always reposition the webview in the screen. Have you tried that?

**Comment by vol24pl** [comment]
Let me explain my setup:

• `captchaView` is a `UIView` made by outlet with hardcoded constraints. It's a  container for `webView`
• inside ` recaptcha?.configureWebView`'s closure there's `webView.frame = self.captchaView.bounds`

Everything is perfectly centered (including `webView` itself) except from a **content** of the `webView`.  Moving `captchaView` to the right so that content in webView seemed centered seems like a hack. Clicking the info icon would make it go even further to the right, and I wouldn't have an easy way to know about the tap, to restore it to the left.

I think there needs to be a method (inside the `configureWebView`'s closure) to center the **content** of the `webView` after `webView`'s frame is set. Maybe something like `webView.evaluateJavaScript(scriptThatCentersTheContent)`

**Comment by fjcaetano** [comment]
The thing is that ReCaptcha's frame within the webview is always rendered at the same size (as far as I could verify) which is a 302x482 box (if you toggle an utility button, the frame's height might grow)

It looks like you're rendering your `captchaView` with a width larger than 302px. Since you want it centralized, it might be the case of fixing its width in 302px. In that case, your centered constraints will have ReCaptcha positioned correctly.

**Comment by vol24pl** [comment]
Thanks! So obvious :)
`             webView.frame = CGRect(center: self.captchaView.bounds.center,
                                    size: CGSize(width: 302, height: self.captchaView.bounds.height))`

worked like a charm! You can add some of this informations to the tutorial though (especially default width).

On a sidenote when using carthage with your lib, to use `forceVisibleChallenge` you need to build carthage package in debug mode: `carthage update --platform iOS --configuration Debug --no-use-binaries`. Please add this to the tutorial. 

Updating binaries of this project to Swift 4.1 would make `--no-use-binaries` not neccessary.

Method `forceVisibleChallenge` is not in "Full Documentation", i knew about it only because I read through closed issues :)

**Comment by fjcaetano** [comment]
@vol24pl glad to know it worked. I'll see if it makes sense to document the ReCaptcha's size.

`forceVisibleChallenge` is not available by default by design. It is not something one would normally want to ship with an app. I see it as a "private API" for debugging.
