### ISSUE TITLE
is it legal 

### ISSUE THREAD

**Issue by AmriApps** [fjcaetano/ReCaptcha#41]
I have question, if this recapacha for ios legal? 

As Apple terms and google terms ?

**Comment by fjcaetano** [comment]
I'm no legal expert, but I don't know of any guidelines or terms of usage for both platforms that this framework may be breaking. I believe the biggest concern would be regarding executing arbitrary code, which ReCaptcha *does not*. For all effects, it's simply a WKWebView displaying web content.

I have publicized apps and I know of third party ones that are currently in the AppStore running this framework. So if your concern is regarding the app not being approved upon review, rest assured ReCaptcha won't be the reason for why it fails.
