### ISSUE TITLE
Only 1 Call every 3-5 minutes

### ISSUE THREAD

**Issue by marcio3457** [fjcaetano/ReCaptcha#45]
During The implementation, i found a issue and didn't know if was an error in API or just my implementation that was incorrect.

I'm defining the webView in This Function 

```
func setupCaptcha(){
        self.recaptcha.configureWebView { [weak self] webview in
            webview.frame = CGRect(x: 5, y: 0, width: (self?.view.bounds.width)!, height: (self?.view.bounds.height)!)
        }
}
```

And Call that function in a TouchUpInside event of a Button called Consultar.

```
@IBAction func onClickConsultar(_ sender: UIButton) {
        self.setupCaptcha()
        validator.validate(self)
}
```

 All of this is done before the call to ReCaptcha.validate function from the API(that is called in the callback method for this function validator.validate)

   
```
override func validationSuccessful() {
        recaptcha.validate(on: self.view, resetOnError: false) { [weak self] (result: ReCaptchaResult) in
            self?.prosseguir(renav: (self?.txtRenavam.text!)!, placa: (self?.txtPlaca.text!)!)
        }
 }
```

And finally, after the return of the ReCaptcha.validate and execution of the above method, i call the ReCaptcha.stop method before transit to the next View Controller.

But, being on the next controller and returning to the previous controller where the button is located, and try to click it again, with the intention of activating again the ReCaptcha.validate method from the API, i only received a message in LOG that says something like : Executing(and don't procede to callback function). After receive this message every time i clicked the button after returning to the controller where it is located, i tried to clicking after a few minutes to see  if it would work, and it worked.

But, 1 validation of ReCaptcha every 3 to 5 minutes is very infeasible.

i do not know if it was my mistake or the API that does not support this or if is correct , can you help me ?

**Comment by fjcaetano** [comment]
You need to call `reset` between each call to `validade`, otherwise the old captcha won't be erased.

Feel free to reopen this issue if necessary.
