### ISSUE TITLE
Install lib

### ISSUE THREAD

**Issue by andrewcookies** [fjcaetano/ReCaptcha#46]
Hi,
How can I import ReCaptcha trough static way?
Is there any Objective C version of library?

Thanks for the support

**Comment by fjcaetano** [comment]
I haven't tried creating a static lib for the project. Doesn't the frameworks generated by Carthage work for you? If not, you'll have to clone the project build it manually anyway.

I don't know of any ObjC version of this lib in particular, but you could always try creating a bridging header to ObjC.
