### ISSUE TITLE
Invisible ReCaptcha always show images

### ISSUE THREAD

**Issue by havebeenfitz** [fjcaetano/ReCaptcha#48]
Hello, I have some issues with invisible reCaptcha. My keys are in place and everything's working as expected, but it always shows the images instead of passing reCaptcha silently. What could be wrong?

I set my preferences to use Invisible one

I also tried to set the `reCaptcha?.forceVisibleChallenge` to` false ` but it didn't help. Is there an issue with my IP address? I also tried to use a different one, but it didn't help either

**Comment by fjcaetano** [comment]
@havebeenfitz It's normal for it to show in the first uses. Google's algorithm might take a few iterations to actually start trusting your client as a valid user instead of a bot.
