### ISSUE TITLE
Bypasssing captcha in UITests

### ISSUE THREAD

**Issue by Przemyslaw-Wosko** [fjcaetano/ReCaptcha#51]
In case where we want to use ReCaptcha in app, then test it with UITests, i think there was no way to "stub" capatcha, to complete for instance sign in flow then make something else in app. 

I created a PR for that #50 

What do you think about this idea? i'm open to changes

**Comment by fjcaetano** [comment]
Great suggestion. This is definitely something I'd like to see merged. I left a few comments on your PR, nothing major.
