### ISSUE TITLE
Alternate endpoint not working

### ISSUE THREAD

**Issue by hqy2000** [fjcaetano/ReCaptcha#55]
When using the alternate endpoint, calling validate will result in nothing. Validate method is also not working. Nothing is logged.

It seems that js script provided by the alternate endpoint is different from that provided by the normal endpoint? Maybe a bug from Google?

**Comment by fjcaetano** [comment]
Hi @mmlmml1 things seem normal on my end. Could you provide more info on what's going on? Maybe some logs and error messages being thrown?

**Comment by hqy2000** [comment]
Tried for several times, still no output.
I will try to set breakpoints to check it later

**Comment by hqy2000** [comment]
Still not clear what happened. But it is working now.
