### ISSUE TITLE
Challenge always gets displayed 

### ISSUE THREAD

**Issue by tzahgr** [fjcaetano/ReCaptcha#57]
Looks like the challenge always gets displayed.
Is this intentional?
If not, do you know why?

**Comment by fjcaetano** [comment]
@tzahgr That might be expected since ReCaptcha may not be able to automatically assess whether or not the user is a client. Usually, after some time it starts resolving invisibly.

I'll close this since it doesn't seem to be an issue, but feel free to reopen if you feel you should.
