### ISSUE TITLE
Change version of RxSwift dependency in podspec

### ISSUE THREAD

**Issue by maxxx777** [fjcaetano/ReCaptcha#58]
Hello,
We are migrating our project from Swift 4.1 to Swift 4.2.
The project and all its dependencies (except ReCaptcha) are using RxSwift 4.4.0. The problem is ReCaptcha 1.4 can not use version 4.4.0 of RxSwift because of `rx.dependency 'RxSwift', '~> 4.3.1'`
May it be replaced with e.g. `rx.dependency 'RxSwift', '~> 4.3'`? (ReCaptcha has no conflicts with RxSwift 4.4.0)

Please let me know if I could make PR to update podspec file.

**Comment by fjcaetano** [comment]
Hi @maxxx777, thanks for the heads up. That seems like a simple enough fix. Do you want to try and tackle that with a PR?

**Comment by maxxx777** [comment]
@fjcaetano thanks for the reply, just did the PR. 
Please let me know if I should update changelog file.
