### ISSUE TITLE
Can you support the objective-c language? 

### ISSUE THREAD

**Issue by Eddiegooo** [fjcaetano/ReCaptcha#62]
Or Is there a library of objective-c versions?

**Comment by fjcaetano** [comment]
Hey @Eddiegooo, you **should** be able to use the library in ObjC using a bridging header. Are you running into any errors? If so, feel free to open an issue with those.

I don't know of any ObjC alternatives and, tbh, it doesn't make sense to either migrate the lib to ObjC, considering you should be able to use it.

I'm closing this issue because it seems there's nothing left to do here, but feel free to reopen it if you want to.

**Comment by Eddiegooo** [comment]
My project was used ObjC, i can not use this repository directly.
use a bridging header  do not work either;   

so i want a pure ObjC repository.

**Comment by Eddiegooo** [comment]
> Hey @Eddiegooo, you **should** be able to use the library in ObjC using a bridging header. Are you running into any errors? If so, feel free to open an issue with those.
> 
> I don't know of any ObjC alternatives and, tbh, it doesn't make sense to either migrate the lib to ObjC, considering you should be able to use it.
> 
> I'm closing this issue because it seems there's nothing left to do here, but feel free to reopen it if you want to.

My project used ObjC, i can not use this repository directly.
use a bridging header do not work either;

so i want a pure ObjC repository.

**Comment by fjcaetano** [comment]
Is the library raising any issues with your bridging header?

**Comment by ralphcorleone** [comment]
@fjcaetano 
Only add this to ReCaptcha.swift
`@objc
public class ReCaptcha : NSObject {`

**Comment by fjcaetano** [comment]
@ralphcorleone as I said before, it doesn't make much sense to officially support Objective-C compatibility, specially considering the current state of Swift vs ObjC.

That said, you're always free to add support to your own fork and manually install the library in your project with the `NSObject` inheritance, if that's what you need.

**Comment by irons163** [comment]
Hi all, 
I made an Objc version of this project:
[ReCaptcha_objc](https://github.com/irons163/ReCaptcha_objc)

Feel free to use it, and welcome to open any issue in that project.
