### ISSUE TITLE
ReCaptcha webview stuck at loading

### ISSUE THREAD

**Issue by edAtRei** [fjcaetano/ReCaptcha#67]
## Bug description

When trying to integrate in my app, after setting up and invoking validate, the 'execute' never gets executed because in `ReCaptchaWebViewManager.execute()`, the "didFinishLoading" variable is always false, so the execute command gets skipped.

I tried the example project to see if I could repro there. I am seeing something similar with the example project, with a caveat. When I load example project, the first time I hit 'validate' it appears to work and I see the Captcha string. However if I hit 'validate' again, the validate never completes. The validate button remains disabled and I see the following statement in the app log.

  "[JS LOG]: executing"

If I kill the example app and start it again, it will again work the first time, but will consistently hang on the second attempt.

## Expected behavior

I would expect the example app 'validate' to work on the second try. I would also expect the integration in my app to load correctly and get to the execute command.

## Additional context

I am looking at this library because our current invisible recaptcha v2 has broken recently. When we try to invoke invisible captcha, our implementation has recently started showing a 'Please upgrade to supported browser' message (using either WKWebView or UIWebView to run the javascript). Looking at this thread https://news.ycombinator.com/item?id=18332549 it appears that there were changes to all versions of ReCaptcha lately. I had assumed that this library would have the same problem we were facing, but my implementation isn't as robust as this libraries. I'm curious if the problem I am seeing with the library/example project are related to this unsupported browser issue.

**Comment by fjcaetano** [comment]
@edAtRei consecutive calls to `validate` are not supported. You need to either instantiate a new ReCaptcha object or call `reset` in between calls.

I'm closing this issue since it doesn't seem to be an actual problem. Feel free to reopen it if you need.

**Comment by Adhith11** [comment]
Thanks @fjcaetano, I got it working.
