### ISSUE TITLE
Usage of arrow functions breaks functionality on <ios 10

### ISSUE THREAD

**Issue by devsaider** [fjcaetano/ReCaptcha#78]
## Bug description
Usage of arrow functions in recaptcha.html breaks iOS 9 support because safari in iOS 9 doesn't support arrow functions in js and maybe something else. 
https://caniuse.com/#feat=arrow-functions 

## To Reproduce
1. Run example app (v1.5.0) on any simulator with <ios 10 (ex. iOS 9)

## Expected behavior
recaptcha.validate() method to work or didFinishLoading callback

## Additional context
It also works if I use recaptcha.html from older version (e.g. 1.4.2)

**Comment by fjcaetano** [comment]
Good catch. Do you think you could work on a PR for this?

**Comment by fjcaetano** [comment]
@devsaider I just opened PR #80 with a possible fix.

Could you point your Podfile to the branch `fix/arrow-func` and check if that fixed your issue?
