### ISSUE TITLE
Error Value of type 'ReCaptcha' has no member 'forceVisibleChallenge'

### ISSUE THREAD

**Issue by PiPyL** [fjcaetano/ReCaptcha#88]
Hello. I meet a issue. It happen when I archive app. It will show error Value of type 'ReCaptcha' has no member 'forceVisibleChallenge'. While I build run test on simulator or real iphone is OK.

**Comment by fjcaetano** [comment]
The `forceVisibleChallenge` is only available in DEBUG builds. You shouldn't be using it in a production application because it defeats the purpose of the Recaptcha being invisible

**Comment by PiPyL** [comment]
So when I release my app, the recaptcha will automatically show images to the user to verify, I don't need to set anything to make it show images?

**Comment by fjcaetano** [comment]
I'm not sure what you meant. You do need to configure the library properly in order for it to work.

The `forceVisibleChallenge` is only meant to be used in development, not in production.
