### ISSUE TITLE
Webview is displayed where it should have been invissible

### ISSUE THREAD

**Issue by Albinzr** [fjcaetano/ReCaptcha#92]
When i ran the my project with code given in documentation, I'm able to see the webview, but it should be invisible. How can i fix this issue?

![image](https://user-images.githubusercontent.com/7425577/84516638-b27c3d00-aceb-11ea-9685-e1e9da8eb6e4.png)

**Comment by fjcaetano** [comment]
From the ReCAPTCHA docs:

> The invisible reCAPTCHA badge does not require the user to click on a checkbox, instead it is invoked directly when the user clicks on an existing button on your site or can be invoked via a JavaScript API call (...) By default only the most suspicious traffic will be prompted to solve a captcha

https://developers.google.com/recaptcha/docs/versions#recaptcha_v2_invisible_recaptcha_badge
