### ISSUE TITLE
Can't get past ReCaptcha - error loading captcha

### ISSUE THREAD

**Issue by bogren** [fjcaetano/ReCaptcha#96]
I can't figure out what goes wrong for a handful of our users. Looking at the custom errors we set up, looks like there is an unexpected error or failed setup. The result is that they can't get past the ReCaptcha and interact with parts of our app. I first thought we did not manage to reset, but turns out the users generate a lot of errors each. 

I appreciate any ideas to help continue debug, or find a solution.

## To Reproduce
I can't reproduce, we see a handful of reports and reported issues in Firebase where we added custom errors.

## Logs
Part of the error logs.

```
6  WebKit                         0x1b7461c0c WTF::Detail::CallableWrapper<-[WKWebView _evaluateJavaScript:forceUserGesture:completionHandler:]::$_7, void, API::SerializedScriptValue*, bool, WebCore::ExceptionDetails const&, WebKit::CallbackBase::Error>::call(API::SerializedScriptValue*, bool, WebCore::ExceptionDetails const&, WebKit::CallbackBase::Error)
7  WebKit                         0x1b7510c50 WebKit::GenericCallback<API::SerializedScriptValue*, bool, WebCore::ExceptionDetails const&>::invalidate(WebKit::CallbackBase::Error)
8  WebKit                         0x1b74cd904 void WebKit::invalidateCallbackMap<WTF::RefPtr<WebKit::CallbackBase, WTF::DumbPtrTraits<WebKit::CallbackBase> > >(WTF::HashMap<unsigned long long, WTF::RefPtr<WebKit::CallbackBase, WTF::DumbPtrTraits<WebKit::CallbackBase> >, WTF::IntHash<unsigned long long>, WTF::HashTraits<unsigned long long>, WTF::HashTraits<WTF::RefPtr<WebKit::CallbackBase, WTF::DumbPtrTraits<WebKit::CallbackBase> > > >&, WebKit::CallbackBase::Error)
9  WebKit                         0x1b74e7f60 WebKit::WebPageProxy::resetState(WebKit::WebPageProxy::ResetStateReason)
10 WebKit                         0x1b74fcf24 WebKit::WebPageProxy::resetStateAfterProcessExited(WebKit::ProcessTerminationReason)
11 WebKit                         0x1b74ef408 WebKit::WebPageProxy::processDidTerminate(WebKit::ProcessTerminationReason)
12 WebKit                         0x1b752c57c WebKit::WebProcessProxy::processDidTerminateOrFailedToLaunch()
13 WebKit                         0x1b752c1b4 WebKit::WebProcessProxy::didClose(IPC::Connection&)
14 WebKit                         0x1b72cf08c WTF::Detail::CallableWrapper<IPC::Connection::connectionDidClose()::$_10, void>::call()
15 JavaScriptCore                 0x1bea4ba3c WTF::RunLoop::performWork()
16 JavaScriptCore                 0x1bea4bcbc WTF::RunLoop::performWork(void*)
```

**Comment by fjcaetano** [comment]
Those logs are internal to WebKit and they may be a duplicate of #77.

There's not much that can be done here, specially because there's not enough data to tackle or even reproduce this issue as you commented. Is it consistent to any specific devices or iOS versions? Would you be comfortable divulging the percentage of your users that are encountering this error? Feel free to email me if you don't want to make that information publicly available.

**Comment by bogren** [comment]
It's not device specific, though iPhone 7 and 6 appear frequently. Happens to our US users on different carriers so we killed the theory of Google getting blocked. The percentage is very low, the impact is high for valid users who we block from interacting with parts of the app. I understand the problem is probably outside of you project. Looking for any leads, solutions or workarounds 😇

**Comment by fjcaetano** [comment]
To be honest there's not much I can help you with. You're only the second person that has encountered that issue. I have never seen that happening myself.

My suggestion for you is the same I gave on #77: keep an eye in [WebKit](https://github.com/WebKit/webkit) and their [Bugzilla](https://bugs.webkit.org/query.cgi?format=specific&product=WebKit) and maybe open a bug there. Also maybe try and get in touch with Google's support?

I'll leave this issue open for a while and, please, post any updates or insights you might have on this.

**Comment by bogren** [comment]
Idk I'm not getting much out of the logs. Closing the issue. If I find something I'll try to remember to share here! 👍
